language: java
jdk: openjdk8

install: true

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  sonarcloud:
    organization: "openapi4j"
    token:
      secure: "KX7DnHVFb35TufoOm3YjXBRVKEPgqX55ttSQw8qzIE5UQyn6O409BKOzEVPbghjClzLyy7nWt1nV7TMibtRpdHgKYHuFaEEk2gy6YLe69bDqHsISTbIPOJ2yjIOvEhZWPCeNBjkxoUnPzyq1NPxDmnVzXbbSlkuML6zFgWeq3Qzcb0QE8ao79Pky5/zpHtcr2eE5oNxS02sv3dJcXDPvo+As4VxzHsmqWDrojwr4OzPur8VxlrrL/m+QhGsUkL7aHAPR5Fu6SmAZ5uoXuoUuP6O+L0qj1HK3dFUM5qGvbyfFKnZGMmE6hIj6kfkowjyOeYygxjCD6ZrIS+quas5yxYgleZmVXbKfVfjPce9r5rMjWDW/bgmd69MEcFEU9mD9PVxo1YgfrAbUIVgxKzp/rUh35tutyXEQKntTC3R4Tl4M3pAkbyLqPbeVrHA4ncW0U76A/OVyKKjLbLMZq9E3YmPQ9vKPp6xAu65SGSkY0ZNpMOmwcdugUTW73BxujefDUAe+Qbnwt3cLi4bpVo/X5uWHkaRXNogTrUoL0Zh+HvcpOuYbgi428CjKYZjSiDrgOBPH4xNYA+YObYuwvHsbh8q2Ki6eLj5AfSQteUy8rIQxW9MitvOtccd0L13QtErPFYtCmTaeuAYo0vTiGJSE5Ixd5TmpsG1RlJoiNkyiK4A="

stages:
  - name: build
  - name: sonarqube
  - name: snapshot
    # only publish snapshots from "master" branch and not in pull requests
    if: branch = master AND type != pull_request
  - name: release
    # only publish releases from "release" branch and not in pull requests
    if: branch = release AND type != pull_request

jobs:
  include:
    # run build
    - stage: build
      script: ./gradlew --no-daemon build jacocoTestReport

    # run sonarqube
    - stage: sonarqube
      script: ./gradlew sonarqube

    # publish snapshot
    - stage: snapshot
      script: ./gradlew --no-daemon publish

    # release stable version
    - stage: release
      script: ./gradlew --no-daemon publish -Drelease=true
